name: widgetbook_workspace
description: "Widgetbook workspace for Stroke Spoiler"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0
  stroke_spoiler:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.20.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
